[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tempdrive"
version = "1.1"
authors = [
    { name="Tamás PEREGI", email="petamas@gmail.com" },
]
description = "Create temporary drive substitutions, just like subst.exe"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "ntstatus>=2.0,<3",
]

[project.urls]
"Homepage" = "https://github.com/petamas/python-tempdrive"
"Bug Tracker" = "https://github.com/petamas/python-tempdrive/issues"
